"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const learningController_1 = require("../controllers/learningController");
const auth_1 = require("../middleware/auth");
const router = (0, express_1.Router)();
router.use(auth_1.requireAuth);
router.get('/', learningController_1.listLearningEntries);
router.get('/today', learningController_1.getTodayLearningEntry);
router.get('/yesterday', learningController_1.getYesterdayLearningEntry);
router.post('/', learningController_1.upsertLearningEntry);
exports.default = router;
